version: '3'
services:
  crawler_test:
    build:
      args:
        user: tester
      context: ./
      dockerfile: Dockerfile
    container_name: crawler_test
    tty: true
    env_file: .env.test
    environment:
      - APP_WORKSPACE=crawler_cd
      - APP_ENV=test
    volumes:
      - ./:/var/www/crawler_cd:cached
    depends_on:
        - crawler_cache_test
    
        
  crawler_cache_test:
    image: redis:alpine
    ports:
      - $REDIS_HOST_PORT:6379
    volumes:
      - crawler_test_cache:/var/cache/data
    environment:
      - REDIS_HOST_PORT=${REDIS_HOST_PORT:-77013}
    container_name: crawler_cache_test
    restart: unless-stopped

volumes:
  crawler_test_cache: {}
